/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bab9.Exception;

import javax.swing.JOptionPane;

/**
 *
 * @author makrusali
 */
public class GUI_BangunDatar extends javax.swing.JFrame {

  /**
   * Creates new form GUI_BangunDatar
   */
  public GUI_BangunDatar() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmbBangunDatar = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    lbInput1 = new javax.swing.JLabel();
    lbInput2 = new javax.swing.JLabel();
    tfInput1 = new javax.swing.JTextField();
    tfInput2 = new javax.swing.JTextField();
    btnProses = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    tfHasil = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    cmbBangunDatar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L. Persegi Panjang", "L. Lingkaran" }));
    cmbBangunDatar.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cmbBangunDatarItemStateChanged(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel1.setText("LUAS BANGUN DATAR");

    lbInput1.setText("Panjang");

    lbInput2.setText("Lebar");

    btnProses.setText("Prosses");
    btnProses.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProsesActionPerformed(evt);
      }
    });

    jLabel4.setText("Hasil");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lbInput2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lbInput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(tfInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(cmbBangunDatar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(13, 13, 13)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(cmbBangunDatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbInput1)
          .addComponent(tfInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbInput2)
          .addComponent(tfInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnProses)
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(67, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cmbBangunDatarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBangunDatarItemStateChanged
    // TODO add your handling code here:
    int index = cmbBangunDatar.getSelectedIndex();
    if (index == 0) {
      tfInput1.setEnabled(true);
      tfInput2.setEnabled(true); 
      lbInput1.setText("Panjang");
      lbInput2.setText("Lebar");
    } else if (index == 1) {
      tfInput1.setEnabled(true);
      tfInput2.setEnabled(false); 
      lbInput1.setText("Jari Jari");
      lbInput2.setText("Lebar");
    }
    
  }//GEN-LAST:event_cmbBangunDatarItemStateChanged

  private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
    // TODO add your handling code here:
    try {
      int index = cmbBangunDatar.getSelectedIndex();
      if (index == 0) {
        int panjang = Integer.parseInt(tfInput1.getText());
        int lebar = Integer.parseInt(tfInput2.getText());
        LuasPersegiPanjang obj = new LuasPersegiPanjang();
        obj.panjang = panjang;
        obj.lebar = lebar;
        double hasil = obj.Luas();
        tfHasil.setText(Double.toString(hasil)); 
      } else if (index == 1) {
        double jariJari = Integer.parseInt(tfInput1.getText());
        LuasLingkaran obj = new LuasLingkaran();
        obj.r = jariJari;
        double hasil = obj.Luas();
        tfHasil.setText(Double.toString(hasil));
      }
    } catch(NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "masukkan nilai angka", "warning", 2);
    } catch(ArithmeticException e) {
      JOptionPane.showMessageDialog(this, "jangan masukkan nilai nil", "warning", 2);
    }

  }//GEN-LAST:event_btnProsesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI_BangunDatar().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnProses;
  private javax.swing.JComboBox<String> cmbBangunDatar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel lbInput1;
  private javax.swing.JLabel lbInput2;
  private javax.swing.JTextField tfHasil;
  private javax.swing.JTextField tfInput1;
  private javax.swing.JTextField tfInput2;
  // End of variables declaration//GEN-END:variables
}
