/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas.Bab9;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author makrusali
 */
public class GUI_RekapBarang extends javax.swing.JFrame {

  /**
   * Creates new form GUI_RekapBarang
   */
  public GUI_RekapBarang() {
    initComponents();
    DefaultTableModel tableModel = (DefaultTableModel)tbInformasiBarang.getModel();
    int row = tableModel.getRowCount();
    while(row > 0) {
      tableModel.removeRow(row - 1);
      row = tableModel.getRowCount();
    }
    showBarangInTable(model.findAll());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    tbInformasiBarang = new javax.swing.JTable();
    tfSearch = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    label8 = new javax.swing.JLabel();
    btnHapus = new javax.swing.JButton();
    btnClose = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tbInformasiBarang.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null}
      },
      new String [] {
        "Kode Barang", "Kategori Barang", "Pemasok", "Pabrikan", "Nama", "Jumlah", "Info 1", "Info 2"
      }
    ));
    jScrollPane2.setViewportView(tbInformasiBarang);

    tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tfSearchKeyReleased(evt);
      }
    });

    jLabel1.setText("Cari 🔍");

    label8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    label8.setText("Rekap Semua Barang");

    btnHapus.setText("Hapus");
    btnHapus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHapusActionPerformed(evt);
      }
    });

    btnClose.setText("Close");
    btnClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCloseActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(label8)
            .addGap(387, 387, 387)
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHapus)
            .addGap(18, 18, 18)
            .addComponent(btnClose)))
        .addContainerGap(15, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label8)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(19, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  BarangSaver model = new BarangSaver();
  
  public void showBarangInTable(List<Barang> barangs) {
    DefaultTableModel tableModel = (DefaultTableModel)tbInformasiBarang.getModel();
    int row = tableModel.getRowCount();
    while(row > 0) {
      tableModel.removeRow(row - 1);
      row = tableModel.getRowCount();
    }
    for (Barang ba : barangs) {
      if (ba instanceof BarangMikroElektronik) {
        // lakukan down casting
        BarangMikroElektronik bme = (BarangMikroElektronik)ba;
        tableModel.addRow(bme.getFields());
      } else if (ba instanceof BarangAlatRumahTangga) {
        // lakukan down casting
        BarangAlatRumahTangga bart = (BarangAlatRumahTangga)ba;
        tableModel.addRow(bart.getFields());
      }
    }
  }
  
  public String getSelectedKodeBarang() {
    int selected = tbInformasiBarang.getSelectedRow();
    DefaultTableModel tableModel = (DefaultTableModel)tbInformasiBarang.getModel();
    return (String)tableModel.getValueAt(selected, 0);
  }
  
  private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
    List<Barang> filteredBarangs = model.findByName(tfSearch.getText());
    showBarangInTable(filteredBarangs);
  }//GEN-LAST:event_tfSearchKeyReleased

  private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
      String selected = getSelectedKodeBarang();
      Barang b = model.findByKodeBarang(selected);
      model.delete(b.getId());
      showBarangInTable(model.findAll());
    } catch(ArrayIndexOutOfBoundsException e) {
      JOptionPane.showMessageDialog(this, "Untuk menghapus pilih barang pada Tabel!!");
    }
  }//GEN-LAST:event_btnHapusActionPerformed

  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    dispose();
  }//GEN-LAST:event_btnCloseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI_RekapBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI_RekapBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI_RekapBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI_RekapBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI_RekapBarang().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnHapus;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel label8;
  private javax.swing.JTable tbInformasiBarang;
  private javax.swing.JTextField tfSearch;
  // End of variables declaration//GEN-END:variables
}
