package Tugas.Bab1;

import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author makrusali
 */
public class GUI_InputBarang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_InputBarang
     */
    public GUI_InputBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label8 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        cbKategoriBarang = new javax.swing.JComboBox<>();
        label4 = new javax.swing.JLabel();
        tfPemasok = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfPabrikan = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplayBarang = new javax.swing.JTextArea();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label8.setText("Informasi Barang");

        label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label3.setText("Kategori Barang");

        cbKategoriBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbKategoriBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sensor", "Mikrokontroller", "Perlatan Rumah Tangga" }));

        label4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label4.setText("Pemasok");

        tfPemasok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        label5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label5.setText("Pabrikan");

        label6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label6.setText("Nama");

        tfNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfPabrikan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        label7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label7.setText("Jumlah");

        tfJumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        taDisplayBarang.setColumns(20);
        taDisplayBarang.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        taDisplayBarang.setRows(5);
        jScrollPane1.setViewportView(taDisplayBarang);

        label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label1.setText("Sistem Inventory Barang Elektronik");

        label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label2.setText("Input Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(label1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3)
                                    .addComponent(label5)
                                    .addComponent(label4)
                                    .addComponent(label6)
                                    .addComponent(label7))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPemasok)
                                    .addComponent(cbKategoriBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNama)
                                    .addComponent(tfPabrikan)
                                    .addComponent(tfJumlah)))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(label2)
                    .addContainerGap(921, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label1)
                .addGap(28, 28, 28)
                .addComponent(label8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3)
                            .addComponent(cbKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5)
                            .addComponent(tfPabrikan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label6)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label7)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnSimpan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(label2)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // variabel list dengan tipe barang
    // penyimpan kumpulan barang
    List<Barang> barangs = new ArrayList<Barang>(); 
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // buat objek barang baru
        Barang inputBarang = new Barang();
        // ambil input barang
        int indexKategoriBarangTerpilih = cbKategoriBarang.getSelectedIndex();
        String kategoriBarangTerpilih = cbKategoriBarang.getItemAt(indexKategoriBarangTerpilih);
        inputBarang.setKategori(kategoriBarangTerpilih);
        inputBarang.setPemasok(tfPemasok.getText());
        inputBarang.setPabrikan(tfPabrikan.getText());
        inputBarang.setNama(tfNama.getText());
        inputBarang.setJumlah(Integer.parseInt(tfJumlah.getText()));
        
        // reset / atur ulang nilai input
        cbKategoriBarang.setSelectedIndex(0);
        tfPemasok.setText("");
        tfPabrikan.setText("");
        tfNama.setText("");
        tfJumlah.setText("");
        
        // proses simpan barang
        barangs.add(inputBarang);
        
        // tampilkan data barang yang tersimpan
        taDisplayBarang.setText("");
        taDisplayBarang.append("Data Barang Masuk...\n");
        taDisplayBarang.append("--------------------------------------------\n");
        taDisplayBarang.append("Kategori : " + inputBarang.getKategori() + "\n");
        taDisplayBarang.append("Pemasok  : " + inputBarang.getPemasok() + "\n");
        taDisplayBarang.append("Pabrikan : " + inputBarang.getPabrikan() + "\n");
        taDisplayBarang.append("Nama     : " + inputBarang.getNama() + "\n");
        taDisplayBarang.append("Jumlah   : " + inputBarang.getJumlah() + "\n");
        
        taDisplayBarang.append("\nRekap Data Barang yang Tersimpan\n");
        taDisplayBarang.append("--------------------------------------------\n");
        
        // tampilkan data barang yang tersimpan dalam variabel barangs
        for (int indexBarang = 0;indexBarang < barangs.size();++indexBarang) {
            Barang barang = barangs.get(indexBarang);
        
            taDisplayBarang.append((indexBarang + 1) + ". " + barang.getNama() + "\n");
            // status barang apakah kosong atau tidak?
            String statusBarang = barang.isKosong() ? "Stock Kosong" : "Tersedia";
            taDisplayBarang.append("   Status   : " + statusBarang + "\n");
            taDisplayBarang.append("   Kategori : " + barang.getKategori() + "\n");
            taDisplayBarang.append("   Pemasok  : " + barang.getPemasok() + "\n");
            taDisplayBarang.append("   Pabrikan : " + barang.getPabrikan() + "\n");
            taDisplayBarang.append("   Jumlah   : " + barang.getJumlah() + "\n\n");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line argu
     * ments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_InputBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKategoriBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JTextArea taDisplayBarang;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfPabrikan;
    private javax.swing.JTextField tfPemasok;
    // End of variables declaration//GEN-END:variables
}
